#+FILETAGs: :work:thesis:

* Thesis Writing
  Notation explanation
  - [X]: stands for checked tasks
  - [ ]: to be done, or stands for original statement is preferred or used, or intact due to confusion in understanding comments
  - [-]: partial revised or pending task. Please check.

  +text+: strike out text

  Click [[file:main.pdf][the latest version]] to open the latest version of thesis.

** DONE I need to sync this to a online doc for Ragnar
   CLOSED: [2020-06-22 Mon 10:44]

** Global Items
   - [X] Capitalize section/chapter~ref
   - [X] Space after Figures/tables. \textfloatset, ref to [[https://tex.stackexchange.com/questions/60477/remove-space-after-figure-and-before-text][here]]
   - [X] Definition formation 1.1,... 4.1
   - [X] The first paragraph of each section/subsection does not indent. I should fix.
   - [X] fix 'maximal likelihood' --> 'maximum likelihood'
   - [X] thesis --> dissertation
   - [X] Capitalization of section titles
   - [ ] Ask someone (phd students) to proofreading.


** Abstract writing and ACKs
   - [-] Abstract
     - [X] Writing
     - [ ] proofreading
   - [-] Swedish
     - [X] Google translate
     - [ ] colleague proofreading
   - [ ] Acknowledgement

** Chapter 2
   Click [[file:comments/c12main.pdf][comments on Chapter1,2]] to open commented file.

   - [X] maximal clique comment in defining MRF, an remark is added after eq(2.3), please check
   - [X] directed and undirected graphical model comparison, comment made on their representation power, thus I did revision. Please check the transition paragraph (discussion from Bayesian network to MRF), right before Example 2.1
   - [X] fix error in eq(2.4). Check if still have difficulty in reading (2.4) (2.5) (2.6)
   - [X] toy model in from three-node to four-node case
   - [X] Section 2.4 Exact Inference is newly added according to comments. Please check


** DONE Chapter 3 [4/8]
   CLOSED: [2020-06-04 Thu 19:44] DEADLINE: <2020-05-29 Fri>
   :LOGBOOK:
   CLOCK: [2020-05-25 Mon 17:27]--[2020-05-25 Mon 17:27] =>  0:00
   :END:

   Click [[file:comments/c3main.pdf][Commented file of Chapter 3]] (c3main.pdf) to open the commented file for this chapter.

   - [X] eq (3.10), (3.11). Not understanding comments
     - [update] This is cleared during our meeting.
   - [X] eq (3.23). Adding one example to symmetric property of potentials, i.e., the Ising model.
   - [X] eq (3.36), +I think it is fine without abs insides, since p-norm operation gives the abs operation by default,+
     - [update] I should use abs value notation over z - z. The correction is made.
   - [-] Interpretation to Theorem and Corollary results. A remark is added (Remark 3.5 in the revised version)
   - [-] quality of the fix point, add one example of coding about :
     - https://documents.epfl.ch/groups/i/ip/ipg/www/2010-2011/Statistical_Physics_for_Communication_and_Computer_Science/mct-new.pdf
     - https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=910578
     - [update] I added a Remark discussing some cases (special graphs or graph structures) where error analysis of BP has been studied, at the end of Theorem 1 (Remark 3.4 in revised).
   - [ ] Figure 3.3, pending
     - Yeah, the order of legend was generated random in the figure where I used a python library. I am leaving the trivial issue pended.
   - [X] page 38 on performance of the prior trick
     - cleared in meeting
   - [ ] corollary 1 comments on page 36 and page 34
     - Studying Corollary 1 with consideration of the presence of the edge/connection probability? (Comment triggered by the pre-fixed edge probability in ER model)
     - yes, I agree that by further taking the edge probability into result (3.43) or (3.44). I also realized this after briefing the LDPC code references in above item. It could be useful when there is application scenarios with random connections of graphs. In practices, when a problem is given, its graphical model is usually fixed. For there cases, it may not be useful to have a convergence condition for random graphs. I am pending this. We can come back to it if the said conditions turn out to be useful for applications.

** Chapter 4
   Click [[file:comments/c45main.pdf][commented Chapter 4,5]] to open your comments on Chapter 4,5

   - [X] Fix eq(4.3), added explanation
   - [-] An example has been add after eq(4.4), showing message update and belief calculation in GBP
   - eq(4.6). The inside term can be formulated in term of KL divergence. I follow the typical definition of region-based free energy. The current definition is fine.
   - eq(4.12), Ragnar questioned where the true b_R comes from.
     b_R here is belief from RENN. It is an estimation instead of ground truth. The regularization is to enforce belief consistency.
   - Ragnar question after eq(4.3). The counting numbers are to balance the each region's energy to the overall region-based free energy. I do not see how this is connected to trees.
     However, a region graph is a hypergraph and is tree-structured by definition. You may see a region graph as a DAG.
   - Response to comment on page 57:
     L2 distance is used for belief regularization in cost function. L1 distance is used for assessment of marginals. It is not typo.
   - [X] +Fix eq(4.7) large {{a, x_a}}, small {{i}}+

** TODO Chapter 5
   - [ ] +Cannot recognize the comment on 'We would begin with the explanation of why inference ...' the last paragraph in preamble of chapter 5.+
   - [ ] *important* I re-did the math and still think the current eq(5.2) (5.4) (5.5) are correct.
   - The question on the remark after eq(5.5).
     Yes, I think a exponential distribution can always be written as log-linear in terms of product between sufficient statistics and natural parameters.
     reference: wainwright2008graphical chapter3 and wiki on exponential family
   - Chapter 5 is supposed to be a transition chapter connecting Inference and Learning, thus I am not planning literature section for this chapter, since all following chapters are about learning.

** TODO Chapter 6
   - [-] revising introducing part for better motivated
     - [X] made changes on emphasizing purpose of increasing flexibility of models
     - [ ] interpolation experiment. It is for illustration of abstraction in latent space and test the invertibility? can not think more on it.

   - [X] section numbering: original depth 2 --> depth 3
   - [X] mixture model in eq (6.9) is defined as a mixture of x. Each component of the mixture should be a density function of x=g_k(z), i.e., p(x=g_k(z)). p denotes the pdf value for any random variable as its argument. Besides, there is no p_z^k for the GenMM model since there is only one latent Gaussian. The randomness then comes from the identity variable as shown in Figure 6.2.
     - [X] Added a bit more explanation before (6.9) for p_k(x).
     - [X] explanation in meeting


** TODO Chapter 7
   - [X] revise the introduction part for better motivation
   - [explanation] There is no need to explicit mention discrete state variables since a dynamic model with continuous latent variable is known as linear dynamical system
   - [explanation] response to the comment right placed after (7.8)
     - Correct, in the inference/computation of posteriors in GenHMM, there is no approximation since forward-backward algorithm is used for the posterior of hidden states computation. Forward-backward algorithm is a message passing algorithm that does exact inference for linear chains.
     - I have added explanation i Remark 7.2 and made connection to the corresponding part in Chapter 2


** TODO Chapter 8



** Conclusion writing
*** DONE Conclusion writing
    CLOSED: [2020-05-27 Wed 16:00]
*** DONE Conclusion polishing
    CLOSED: [2020-06-10 Wed 10:12]



* TODO Committee Candidate List
  Schorlar https://scholar.google.se/citations?view_op=search_authors&mauthors=lars&hl=sv&oi=ao

  Search a bit more.

  For a grading committee consisting of three members, at least two members must be sourced outside of KTH. For a grading committee consisting of five members, at least three members must be sourced outside of KTH. Clarification: the opponent is not in the grading committee

  Two substitute members (stand-ins) of the grading committee for public defences of doctoral theses must be appointed (both substitutes cannot come from KTH if one of the ordinary members of the grading committe is already from KTH).

  Three external committee members + two KTH subsitutes (one of them to be the advance reviewer, check).

  ** *We should start from next week's meeting for contacting the committees, I should put more candidates here*

  - [ ] Timo Koski, Professor emeritus of mathematical statistics, KTH,
    [[https://people.kth.se/~tjtkoski/][KTHProfile Page]],
    [[https://scholar.google.com/citations?hl=en&user=1CuzidAAAAAJ&view_op=list_works&sortby=pubdate][Google scholar]]. Or check his colleagues.
    [[https://www.math.kth.se/matstat/staff_e.html][KTH Mathematics]]
    Seems retired

  - [Preferred] Erik Aurell, KTH
    keywords: Biological, PhysicsNon-equilibrium Physics, Inference, Big Data
    [[http://www.csc.kth.se/forskning/cb/cbp/homepages/eaurell/kth_homepage.html][kth page]]

  - [ ] Nicolas Macris, EPFL
    Keywords, Theory of error correcting codes, statistical mechanics and information theory
    [[https://people.epfl.ch/nicolas.macris][Page]]

  - [ ] Hossein Azizpour, Assistant Professor in Machine Learning, Division of Robotics, Perception, and Learning (RPL)
    Deep learning, understanding its techniques, and advancing them particularly through equpping them with reasoning, inductive biases, uncertainty estimation and knowledge transfer.
    [[https://www.kth.se/profile/azizpour][Page]]

  - [ ] John Folkesson, Associate Professor and Docent at  the division of Robots Perception and Learning, KTH
    In the area of mobile robotics
    [[https://www.kth.se/profile/johnf][Page]]

  - [ ] Hedvid kjellstrom, KTH
    Keywords: Computer Vision, Machine Learning, Representation Learning, Human Behavior, Animal Behavior
    [[https://scholar.google.com/citations?hl=en&user=wr3CtKAAAAAJ&view_op=list_works&sortby=pubdate][Google scholar]]

  - [ ] Henk Wymeersch, Communication Systems, Chalmers
    [[https://www.chalmers.se/en/staff/Pages/henk-wymeersch.aspx][Page]] ,
    [[https://sites.google.com/site/hwymeers/][Google site]]

  - uppsalar, there maybe groups

  - [ ] Bogdan Savchynskyy, Senior Researcher and Group Leader (Akademischer Rat) at Visual Learning Lab, Universität Heidelberg
    [[https://hci.iwr.uni-heidelberg.de/vislearn/people/bogdan/][Page]]

** picked up from google scholar
  - Fredrik Lindsten, Associate Professor in Machine Learning, Associate Professor at the Division of Statistics and Machine Learning, the Department of Computer and Information Science, Linköping University 

    page: https://lindsten.netlify.app/aboutme/
    google scholar: https://scholar.google.se/citations?user=RfTyvdsAAAAJ&hl=sv
    
  - Thomas Schön, Uppsalar,
    [[http://user.it.uu.se/~thosc112/][page]]
    [[https://scholar.google.se/citations?hl=sv&user=FUqUC2oAAAAJ&view_op=list_works&sortby=pubdate][Scholar]]


* Schedule for Defense

  Schedule following: [KTH public defense of doctoral thesis](https://intra.kth.se/en/eecs/forskarutbildning/public-defence-of-doctoral-thesis-1.813458)
  - [X] **March**: course credit fulfilling check.
  - [X] **March**: Check with Ragnar about the preliminary drafting stuff.
  - [X] **March**: ~~preliminary Content organizing~~ We decide revise content organizing while along writing content.
  - [X] **March-May**: Finish the first complete draft of thesis.
    - [X] **March-April**: Introduction, Background, Inference Part finished
    - [X] **April-May**: Learning Part,
    - [ ]abstract, acknowledgements
  - [X] **March-May**: Finish the first complete draft of thesis.

  - Considering that summer break **16 June -- 14 August** is not taken into account into KTH public defense procedure

  - [ ] **Mid June -- Mid August** parallel tasks:
    - [ ] **Before 15 August** committee member confirm. Lars and Ragnar.
    - [ ] quality reviewer contact. Lars and Ragnar
    - [OnGoing Now] **June-August**: Improving and revising thesis.

  - [ ] **17--19 August** (34th week) Start the standard process (10-week procedure). Revise eISP, thesis preliminary version, advance reviewer.
  - [ ] **14--18 September** (38th week) eISP in right status, advance reviewer and preliminary version to thesis to advance reviewer ... preprint of thesis
  - [ ] **28 September -- 9 October** (40th-41th week) Lars, Ragnar work with doctoral-education-support for arrangement stuff. Thesis digital processing and printing.
  - [ ] **Mid October--7th November, the 45th week** (The time ranges to tolerate the availability of committee) Defense.
